// Copyright 2022 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


#define XXX KC_NO

#define LAYOUT( \
    K20, K0E, K02, K0B, K00, K01, K0C, K0D, \
    K41, K1E, K1A, K10, K11, K1B, K1C, K1D, \
    K42, K2E, K21, K22, K2B, K2C, K2D, \
    K31, K32, K3B, K3C, K3D, K3E, \
    K43, K4B, K4C, K4E, \
    K52, K53, K5D, K5E, K4D, K03, K04, K05, K06, \
    K12, K13, K14, K15, \
    K23, K24, K25, K26, \
    K33, K34, K35, K36, \
    K46, K48, K45, K07, K08, K09, K0A, \
    K16, K17, K18, K19, \
    K27, K28, K29, K2A, \
    K37, K38, K39, K3A, \
    K49, K4A  \
) { \
    { K00, K01, K02, K03, K04, K05, K06, K07, K08, K09, K0A, K0B, K0C, K0D, K0E }, \
    { K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K1B, K1C, K1D, K1E }, \
    { K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K2B, K2C, K2D, K2E }, \
    { XXX, K31, K32, K33, K34, K35, K36, K37, K38, K39, K3A, K3B, K3C, K3D, K3E }, \
    { XXX, K41, K42, K43, XXX, K45, K46, XXX, K48, K49, K4A, K4B, K4C, K4D, K4E }, \
    { XXX, XXX, K52, K53, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, XXX, K5D, K5E }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
